# Generated by Django 3.1.3 on 2020-11-22 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerId', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=7)),
                ('incomeGroup', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=10)),
                ('marital_status', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')])),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('policyId', models.AutoField(primary_key=True, serialize=False)),
                ('purchaseDate', models.DateField()),
                ('premium', models.DecimalField(decimal_places=0, max_digits=7)),
                ('fuel', models.CharField(max_length=10)),
                ('vehiclesegment', models.CharField(max_length=1)),
                ('bodilyInjuryLiability', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')])),
                ('personalInjuryProtection', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')])),
                ('collision', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')])),
                ('comprehensive', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
            ],
        ),
    ]
