# Generated by Django 3.1.3 on 2020-11-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policy',
            old_name='vehiclesegment',
            new_name='vehicleSegment',
        ),
        migrations.AddField(
            model_name='policy',
            name='propertyDamageLiability',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0),
            preserve_default=False,
        ),
    ]
