# Generated by Django 3.1.3 on 2020-11-23 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201122_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='bodilyInjuryLiability',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], editable=False),
        ),
        migrations.AlterField(
            model_name='policy',
            name='collision',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], editable=False),
        ),
        migrations.AlterField(
            model_name='policy',
            name='comprehensive',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], editable=False),
        ),
        migrations.AlterField(
            model_name='policy',
            name='customer',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.customer'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='fuel',
            field=models.CharField(editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='policy',
            name='personalInjuryProtection',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], editable=False),
        ),
        migrations.AlterField(
            model_name='policy',
            name='premium',
            field=models.DecimalField(decimal_places=0, editable=False, max_digits=7),
        ),
        migrations.AlterField(
            model_name='policy',
            name='propertyDamageLiability',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], editable=False),
        ),
        migrations.AlterField(
            model_name='policy',
            name='purchaseDate',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='policy',
            name='vehicleSegment',
            field=models.CharField(editable=False, max_length=1),
        ),
    ]
