# Generated by Django 3.1.3 on 2020-11-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201123_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='premium',
            field=models.DecimalField(decimal_places=0, max_digits=7),
        ),
    ]
