# Generated by Django 3.1.3 on 2020-11-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201123_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='fuel',
            field=models.CharField(max_length=10),
        ),
    ]
